---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss1
spec:
  serviceName: dbsvc
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: cont1
          image: sriramk16/opdb
          ports:
            - containerPort: 80

          volumeMounts:
           - name: dbvol
             mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: dbvol
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi


