---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubernetes.io/change-cause: "deploying Stateful"
  name: ss1
spec:
  replicas: 2
  selector:
     matchLabels:
       app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: cont1
          image: sriramk16/opdb
          ports:
            - containerPort: 3306

          volumeMounts:
            - name: db-backup
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db-backup
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
         storage: 2Gi


