apiVersion: v1
kind: Pod
metadata:
  name: restricted-pod
  namespace: restricted-ns
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: cont1
      image: busybox
      command: ["sleep", "6000"]
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "100m"
          memory: "256Mi"
        requests:
          cpu: "50m"
          memory: "156Mi"
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
        capabilities:
          drop: ['ALL']
