apiVersion: v1
kind: Pod
metadata:
  name: hp-pod
spec:
  priorityClassName: high-priority
  containers:
  - name: nginx-cont
    image: nginx
    resources:
      limits:
        cpu: "350m"
        memory: "356Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"

