---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: cont1
      image: nginx

      envFrom:
        - configMapRef:
            name: cm1
        - secretRef:
            name: sec1
      env:
        - name: Api_Token
          valueFrom:
            secretKeyRef:
              name: sec2
              key: API_TOKEN
        - name: Client
          valueFrom: 
             configMapKeyRef:
               name: cm2
               key: CLIENT
