apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cont1
              image: ubuntu
              command:
                - sh
                - -c
                - |
                  echo "logrotating and compressing file"
                  sleep 30
                  echo "Done"
