apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: env
                operator: NotIn
                values: 
                - dev
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80

