apiVersion: v1
kind: Pod
metadata:
  name: pod4
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: env
                operator: In
                values: 
                - dev
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80

