apiVersion: v1
kind: Pod
metadata:
  name: pod6
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
              - db
        topologyKey: kubernetes.io/hostname
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80

