apiVersion: v1
kind: Pod
metadata:
  name: pod10
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app: db
            topologyKey: kubernetes.io/hostname
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80
