apiVersion: v1
kind: Pod
metadata:
  name: pod17
  labels:
    app: db
spec:
  containers:
    - name: cont1
      image: mariadb:10.6
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
