apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devtest
spec:
  destination:
    namespace: ecom
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  source:
    path: argocd-deploy
    repoURL: https://github.com/Kajjayamsriram/k8s-objects.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
